{
 "title": "k8s-1m",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Machine count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_boot_time_seconds) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Scheduling attempt rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_pod_scheduling_attempts_count)) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduling time rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_scheduling_algorithm_duration_seconds_sum)) by (job) / sum(rate(scheduler_scheduling_algorithm_duration_seconds_count)) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods scheduled total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(scheduler_pod_scheduling_attempts_count) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "avg(go_goroutines{job=\"dist-scheduler\"}) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod queue len",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kubernetes.container_name:relay \"Processing pod\" | unpack_logfmt | queue_len:>0 | stats by(_time:1s) min(queue_len)"
    }
   ]
  },
  {
   "title": "User CPU-secs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_user_cpu_seconds_total{job=\"dist-scheduler\"})) by (job, kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time by plugin",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_plugin_execution_duration_seconds_sum{}) / rate(scheduler_plugin_execution_duration_seconds_count{})) by (job, plugin\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu-secs according to cadvisor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{container=\"dist-scheduler\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_cpu_usage_seconds_total{container=\"relay\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_sched_latencies_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "avg(go_sched_latencies_seconds_sum{job=\"dist-scheduler\"}) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"dist-scheduler\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Pods approved/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "kubernetes.container_name:dist-scheduler \"Permit approved\" | stats rate()"
    }
   ]
  },
  {
   "title": "known node count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    { "expr": "distscheduler_node_count", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * rate(distscheduler_schedule_one_time_seconds) / rate(distscheduler_schedule_one_count)",
     "legendFormat": "Schedule - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(1000 * rate(distscheduler_wait_for_subscheduler_time_seconds) / rate(distscheduler_schedule_one_relay_count)) by (kubernetes_pod_name) > 0.001",
     "legendFormat": "Wait - {{kubernetes_pod_name}}"
    },
    {
     "expr": "1000 *  rate(distscheduler_schedule_one_relay_time_seconds) / rate(distscheduler_schedule_one_relay_count) > 0.01",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "ScheduleOne time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(distscheduler_schedule_one_time_seconds) / rate(distscheduler_schedule_one_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dist-scheduler logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "kubernetes.container_name:dist-scheduler"
    }
   ]
  },
  {
   "title": "node exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "load1",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "node_load1 * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Active memory %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(node_memory_Active_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"})) by (host, mode)",
       "legendFormat": "{{host}} - {{mode}}"
      }
     ]
    },
    {
     "title": "CPU seconds (user)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 84 },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\"})) by (instance) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU seconds (non-idle)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 84 },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"})) by (instance) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Idle CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"})) by (instance) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU seconds (non-idle) stacked",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"})) by (instance) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "network rx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "8 * sum(rate(node_network_receive_bytes_total{device!~\".*br.*\",device!~\"veth.+\"})) by (instance, host) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "network tx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "8 * sum(rate(node_network_transmit_bytes_total{device!~\".*br.*\",device!~\"veth.+\"})) by (instance, host, device) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}} {{device}}"
      },
      {}
     ]
    },
    {
     "title": "node_nf_conntrack_entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries  * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "TCP flow open rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "(rate(node_netstat_Tcp_ActiveOpens) + rate(node_netstat_Tcp_PassiveOpens)) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "node_netstat_Tcp_CurrEstab",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 126 }, "options": { "content": "<center><h2>Disk</h2></center>" } },
    {
     "title": "node_disk_writes_completed_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "sum(rate(node_disk_writes_completed_total)) by (instance) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "node_disk_written_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total)) by (instance) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  { "title": "etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "mem_etcd_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(mem_etcd_requests_total)) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "mem_etcd_tree_map_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Item count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sort(avg(mem_etcd_tree_map_item_count) by (prefix))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request timings p99.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(mem_etcd_request_latency_seconds_bucket{type!=\"watch\"}[$__rate_interval])) by (type, le)) < .002",
     "legendFormat": "p99.9 {{type}}"
    }
   ]
  },
  {
   "title": "Queries > Xs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "sum(rate(mem_etcd_request_latency_seconds_bucket{le=\"+Inf\"}[$__interval]) - on(type) rate(mem_etcd_request_latency_seconds_bucket{le=\"0.1\"}[$__interval]))",
     "legendFormat": "100ms"
    },
    {
     "expr": "sum(rate(mem_etcd_request_latency_seconds_bucket{le=\"+Inf\"}[$__interval]) - on(type) rate(mem_etcd_request_latency_seconds_bucket{le=\"0.5\"}[$__interval]))",
     "legendFormat": "500ms"
    }
   ]
  },
  {
   "title": "Set",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum(rate(mem_etcd_request_latency_seconds_bucket{type=\"set\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Range",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "sum(rate(mem_etcd_request_latency_seconds_bucket{type=\"range\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compacted revision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "mem_etcd_compacted_revision_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current revision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "mem_etcd_revision_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mem_etcd_lock_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "mem_etcd_lock_count",
     "legendFormat": "{{structure}} {{method}} {{rw}}"
    }
   ]
  },
  {
   "title": "num watchers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "targets": [
    { "expr": "mem_etcd_watcher_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mem_etcd_lock_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "mem_etcd_lock_seconds",
     "legendFormat": "{{structure}} {{method}} {{rw}}"
    }
   ]
  },
  {
   "title": "Response sizes bits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(mem_etcd_watch_response_bytes) * 8",
     "legendFormat": "watch {{prefix}}"
    },
    {
     "expr": "rate(mem_etcd_range_response_bytes) * 8",
     "legendFormat": "range {{prefix}}"
    }
   ]
  },
  {
   "title": "response count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(mem_etcd_watch_response_count)",
     "legendFormat": "watch {{prefix}}"
    },
    {
     "expr": "rate(mem_etcd_range_response_count)",
     "legendFormat": "range {{prefix}}"
    }
   ]
  },
  {
   "title": "range response count / request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": " sum(rate(mem_etcd_range_response_count)) / sum(rate(mem_etcd_requests_total{type=\"range\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem_etcd_watch_response_blocking_time_seconds & count (cumulative, not rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "mem_etcd_watch_response_blocking_time_seconds",
     "legendFormat": "blocking_time_seconds {{prefix}}"
    },
    {
     "expr": "mem_etcd_watch_response_blocking_count",
     "legendFormat": "blocking_count {{prefix}}"
    }
   ]
  },
  {
   "title": "mem_etcd_in_flight_requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "mem_etcd_in_flight_requests", "legendFormat": "mem_etcd_in_flight_requests" }
   ]
  },
  {
   "title": "mem_etcd_watch_channel_latest_revision",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(mem_etcd_watch_channel_latest_revision{prefix=\"/registry/leases/\"}) by (remote_addr, watch_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "apiserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 } },
  {
   "title": "API server request count",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_count{verb!=\"WATCH\"})) by (resource, verb)",
     "legendFormat": "{{resource}} - {{verb}}"
    }
   ]
  },
  {
   "title": "apiserver request latency p95 for rate >=10qps",
   "type": "timeseries",
   "description": "etcd request latency (p95)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{verb!=\"WATCH\"}[5m])) by (le, resource, verb)) and on(resource, verb) (rate(apiserver_request_duration_seconds_count) >= 10)",
     "legendFormat": "{{resource}} - {{verb}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API server total request duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb!=\"WATCH\"})) by (resource, verb)",
     "legendFormat": "{{resource}} - {{verb}}"
    }
   ]
  },
  {
   "title": "API server request count LIST only",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_count{verb=\"LIST\"})) by (resource, verb)",
     "legendFormat": "{{resource}} - {{verb}}"
    }
   ]
  },
  {
   "title": "API server total request duration stacked",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb!=\"WATCH\"})) by (resource, verb) > 0",
     "legendFormat": "{{resource}} - {{verb}}"
    }
   ]
  },
  {
   "title": "apiserver request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total)) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "apiserver request latency",
   "type": "timeseries",
   "description": "95th percentile request latency for Kubernetes apiserver component",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[1m])) by (le))",
     "legendFormat": "p50 "
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[1m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "puts by resource",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{verb=\"PUT\"})) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "apiserver request rate by instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 218 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total)) by (instance)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "etcd_request_duration_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 218 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(etcd_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "LISTs",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 218 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket{verb=\"LIST\"})) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "non-2xx apiserver requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code!~\"2.*\"})) by (resource, code) > 0",
     "legendFormat": "{{resource}} {{code}}"
    }
   ]
  },
  {
   "title": "Top 10 highest total processing time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(apiserver_request_duration_seconds_sum{verb!=\"WATCH\"})) by (resource, verb))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_current_inflight_requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 236 },
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top watch events by resource",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(apiserver_watch_events_total)) by (kind))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 highest request rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(apiserver_request_duration_seconds_count{verb!=\"WATCH\"})) by (resource, verb))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watches by resource",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(100, sum(apiserver_longrunning_requests{verb=\"WATCH\"}) by (resource))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"k3s\", host=\"apiserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(go_memstats_alloc_bytes{job=~\"(k3s|kube-scheduler|kube-controller-manager)\"}, \"instance\", \"$1:1010\", \"instance\", \"(.+):.+\") * on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}} - {{job}}"
    },
    {
     "expr": "container_memory_rss{container=\"traefik\"}",
     "legendFormat": "traefik"
    }
   ]
  },
  {
   "title": "go_sched_latencies_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_sched_latencies_seconds_sum{job=\"k3s\", host=\"apiserver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubelet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 270 },
   "collapsed": true,
   "panels": [
    {
     "title": "go_memstats_alloc_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2104 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=~\"k3s.*\", host=\"kubelets\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "container_memory_rss",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2104 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "quantile(0.5, container_memory_rss{job=\"kubelet-cadvisor\", container=\"kubelet\"})",
       "legendFormat": "p50"
      },
      {
       "expr": "quantile(0.95, container_memory_rss{job=\"kubelet-cadvisor\", container=\"kubelet\"})",
       "legendFormat": "p95"
      },
      {
       "expr": "min(container_memory_rss{job=\"kubelet-cadvisor\", container=\"kubelet\"})",
       "legendFormat": "p0"
      },
      {
       "expr": "max(container_memory_rss{job=\"kubelet-cadvisor\", container=\"kubelet\"})",
       "legendFormat": "p100"
      },
      {
       "expr": "avg(container_memory_rss{job=\"kubelet-cadvisor\", container=\"kubelet\"})",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  { "title": "kwok", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 271 } },
  {
   "title": "Kwok oldest rev rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 272 },
   "targets": [
    {
     "expr": "rate(kwok_node_lease_delay_percentile{percentile=\"oldest_rev\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kwok_node_lease_delay_percentile max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 272 },
   "targets": [
    {
     "expr": "avg(kwok_node_lease_delay_percentile{percentile=\"1.0\"} > 0) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_watch_cache_resource_version rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
   "targets": [
    {
     "expr": "apiserver_watch_cache_resource_version{resource=\"leases.coordination.k8s.io\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_watch_events_total Lease",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 280 },
   "targets": [
    {
     "expr": "avg(rate(apiserver_watch_events_total{kind=\"Lease\"})) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max apiserver_watch_cache_store_lock_seconds rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
   "targets": [
    {
     "expr": "max(rate(apiserver_watch_cache_store_lock_seconds{resource=\"storage/cacher.go:/leases\"})) by (rw, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vicky",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 296 },
   "collapsed": true,
   "panels": [
    {
     "title": "VictoriaLogs free disk space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2458 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "vl_free_disk_space_bytes", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}